title: "PyTSMod: A Python Implementation of Time-Scale Modification Algorithms"
institution: Music and Audio Computing Lab., KAIST
author: Sangeon Yong and Juhan Nam
show_downloads: true

baseurl: "/PyTSMod-ISMIR2020LBD" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://seyong92.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

github:
  repository_url: https://github.com/KAIST-MACLab/PyTSMod
  paper_url: "about:blank"
  video_url: "about:blank"
